use crate::db::schema::*;
use diesel::prelude::*;
// Generated by diesel_ext

#[derive(Queryable, Debug)]
pub struct Playlist {
    pub name: String,
}

#[derive(Insertable)]
#[diesel(table_name = playlist)]
pub struct NewPlaylist<'a> {
    pub name: &'a str,
}

#[derive(Queryable, Debug)]
#[diesel(primary_key(playlist_id, song_id))]
pub struct PlaylistSong {
    pub playlist_id: String,
    pub song_id: String,
}

#[derive(Insertable)]
#[diesel(table_name = playlist_song)]
pub struct NewPlaylistSong<'a> {
    pub playlist_name: &'a str,
    pub song_id: &'a str,
}

#[derive(Queryable, Debug)]
pub struct Song {
    pub id: String,
    pub name: String,
    pub artist: Option<String>,
}

#[derive(Insertable)]
#[diesel(table_name = song)]
pub struct NewSong<'a> {
    pub id: &'a str,
    pub name: &'a str,
    pub artist: Option<String>,
}
